# Generated by ishou-render::nix — DO NOT EDIT
# Source of truth: pleme-io/ishou/crates/ishou-tokens/src/color.rs
# Architecture:    pleme-io/theory/THEME-ARCHITECTURE.md
# Shape compatible with the legacy
# `<wrapper>/module/themes/nord/colors.nix` files this output
# replaces — import the package and consume identically.
{
  polar = {
    night0 = "#2E3440";
    night1 = "#3B4252";
    night2 = "#434C5E";
    night3 = "#4C566A";
  };

  snow = {
    storm0 = "#D8DEE9";
    storm1 = "#E5E9F0";
    storm2 = "#ECEFF4";
  };

  frost = {
    frost0 = "#8FBCBB";
    frost1 = "#88C0D0";
    frost2 = "#81A1C1";
    frost3 = "#5E81AC";
  };

  aurora = {
    red = "#BF616A";
    orange = "#D08770";
    yellow = "#EBCB8B";
    green = "#A3BE8C";
    purple = "#B48EAD";
  };
}
